spring:
    redis:
        host: 127.0.0.1
        port: 6379
        password:
        timeout: 5000
        jedis:
            pool:
                max-active: 200     #连接池最大连接数（使用负值表示没有限制）
                max-idle: 10        # 连接池中的最大空闲连接
                max-wait: -1        # 连接池最大阻塞等待时间（使用负值表示没有限制）
                min-idle: 0         # 连接池中的最小空闲连接
        database: 4

    datasource:
        type: com.alibaba.druid.pool.DruidDataSource                                #  配置当前要使用的数据源的操作类型
        driver-class-name: com.mysql.jdbc.Driver                                    #  配置mysql的驱动程序类
        url: jdbc:mysql://127.0.0.1:3306/zust_website?useUnicode=true&characterEncoding=utf8 #  数据库连接地址
        username: root                                                              #  数据库用户名
        password: 123456
        #  数据库密码
        druid:
            filters: stat
            initialSize: 5
            minIdle: 5
            maxActive: 20
            maxWait: 60000
            timeBetweenEvictionRunsMillis: 60000                                      # timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000                                        # 配置一个连接在池中最小生存的时间，单位是毫秒
            validationQuery: SELECT 1 FROM DUAL
            testWhileIdle: true
            testOnBorrow:  false
            testOnReturn:  false

eureka:
    client:
        serviceUrl:
            defaultZone: http://127.0.0.1:8761/eureka/
        register-with-eureka: true
        fetch-registry: true


